/**
 * Documentación completa de la API v1.
 * GET /api/v1/documentacion devuelve este objeto en JSON.
 * Incluye endpoints, parámetros, ejemplos de cuerpo/respuesta y pruebas (curl).
 */
const { ESTADOS_PIPELINE, CANALES_ORIGEN, PRIORIDADES } = require('./models/lead.model');
const interaccionModel = require('./models/interaccion.model');
const tareaModel = require('./models/tarea.model');
const TIPOS_INT = interaccionModel.TIPOS;
const DIRECCIONES = interaccionModel.DIRECCIONES;
const RESULTADOS = interaccionModel.RESULTADOS;
const TIPOS_TAREA = tareaModel.TIPOS;
const ESTADOS_TAREA = tareaModel.ESTADOS;

const reglasNegocio = [
  'Lead: No permitir duplicados por mismo teléfono o mismo email (si existe).',
  'Lead: Ticket estimado ≥ 0. Lead puede tener clienteId (trazabilidad al convertir en cliente).',
  'Lead: No se puede tener estado cerrado/perdido con activo = true; al pasar a cerrado/perdido se marca activo = false.',
  'Lead: Al crear una interacción de un lead, se actualiza automáticamente ultimoContacto del lead.',
  'Lead: Si estadoPipeline = propuesta, debe existir al menos una interacción previa.',
  'Lead: Convertir en cliente (POST /leads/get/:id/convertir-cliente): crea cliente, evita duplicados, marca lead inactivo y guarda clienteId.',
  'Cliente: No duplicados por email/teléfono. MRR ≥ 0. leadOrigenId opcional (si viene de lead).',
  'Interacción: proximaAccionFecha no puede ser anterior a fechaInteraccion.',
  'Interacción: No permitir interacción para lead inexistente. Si resultado = interesado, se crea automáticamente una tarea de seguimiento.',
  'Tarea: No permitir completada = true si estado no es hecha. fechaRecordatorio no puede ser posterior a fechaVencimiento. Una tarea no puede tener leadId y clienteId a la vez. categoriaPlanificacion obligatoria (default puntual). repeticion coherente con categoría (daily→diaria, weekly→semanal).',
];

function buildDoc(baseUrl = 'http://localhost:3000') {
  const base = `${baseUrl}/api/v1`;
  const enc = (s) => (s ? encodeURIComponent(s) : '');

  const endpoints = [
    // Health
    {
      metodo: 'GET',
      ruta: '/api/v1/health',
      descripcion: 'Estado de la API y proveedor de datos (memory | mongo).',
      pathParams: [],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, message: 'NakedCRM Lite API', provider: 'memory' },
      prueba: `curl -s "${baseUrl}/api/v1/health"`,
    },
    // Leads
    {
      metodo: 'GET',
      ruta: '/api/v1/leads/get/all',
      descripcion: 'Obtener todos los leads.',
      pathParams: [],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: [{ id: '...', nombre: '...', empresa: '...', telefono: '...', email: '...', canalOrigen: 'web', estadoPipeline: 'nuevo', ticketEstimado: 1000, prioridad: 'media', activo: true, createdAt: '...', updatedAt: '...' }] },
      prueba: `curl -s "${base}/leads/get/all"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/leads/get/all/paginated',
      descripcion: 'Leads paginados con filtros opcionales.',
      pathParams: [],
      queryParams: [
        { nombre: 'page', tipo: 'number', opcional: true, ejemplo: '1', descripcion: 'Página' },
        { nombre: 'limit', tipo: 'number', opcional: true, ejemplo: '10', descripcion: 'Registros por página' },
        { nombre: 'search', tipo: 'string', opcional: true, descripcion: 'Búsqueda en nombre, empresa, email, teléfono' },
        { nombre: 'estadoPipeline', tipo: 'string', opcional: true, enum: ESTADOS_PIPELINE, descripcion: 'Filtrar por estado' },
        { nombre: 'prioridad', tipo: 'string', opcional: true, enum: PRIORIDADES, descripcion: 'Filtrar por prioridad' },
        { nombre: 'canalOrigen', tipo: 'string', opcional: true, enum: CANALES_ORIGEN, descripcion: 'Filtrar por canal' },
        { nombre: 'fechaCreacionDesde', tipo: 'string', opcional: true, descripcion: 'Fecha creación desde (ISO)' },
        { nombre: 'fechaCreacionHasta', tipo: 'string', opcional: true, descripcion: 'Fecha creación hasta (ISO)' },
        { nombre: 'ultimoContactoDesde', tipo: 'string', opcional: true, descripcion: 'Último contacto desde (ISO)' },
        { nombre: 'ultimoContactoHasta', tipo: 'string', opcional: true, descripcion: 'Último contacto hasta (ISO)' },
        { nombre: 'ticketMin', tipo: 'number', opcional: true, descripcion: 'Ticket estimado mínimo' },
        { nombre: 'ticketMax', tipo: 'number', opcional: true, descripcion: 'Ticket estimado máximo' },
      ],
      requestBody: null,
      responseExample: { ok: true, data: [], meta: { page: 1, limit: 10, total: 20, totalPages: 2 } },
      prueba: `curl -s "${base}/leads/get/all/paginated?page=1&limit=5"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/leads/get/export/csv',
      descripcion: 'Exportar todos los leads en CSV.',
      pathParams: [],
      queryParams: [],
      requestBody: null,
      responseExample: '(Contenido CSV en texto)',
      prueba: `curl -s "${base}/leads/get/export/csv" -o leads.csv`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/leads/get/:id',
      descripcion: 'Obtener un lead por ID.',
      pathParams: [{ nombre: 'id', tipo: 'string', descripcion: 'ID del lead' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: { id: '...', nombre: '...', empresa: '...', telefono: '...', email: '...', canalOrigen: 'web', estadoPipeline: 'nuevo', ticketEstimado: 1000, prioridad: 'media', activo: true, fechaAlta: '...', ultimoContacto: null, createdAt: '...', updatedAt: '...' } },
      prueba: `curl -s "${base}/leads/get/REEMPLAZAR_ID"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/leads/get/:id/interacciones',
      descripcion: 'Interacciones del lead.',
      pathParams: [{ nombre: 'id', tipo: 'string', descripcion: 'ID del lead' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: [] },
      prueba: `curl -s "${base}/leads/get/REEMPLAZAR_ID/interacciones"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/leads/get/:id/tareas',
      descripcion: 'Tareas asociadas al lead.',
      pathParams: [{ nombre: 'id', tipo: 'string', descripcion: 'ID del lead' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: [] },
      prueba: `curl -s "${base}/leads/get/REEMPLAZAR_ID/tareas"`,
    },
    {
      metodo: 'POST',
      ruta: '/api/v1/leads/post',
      descripcion: 'Crear un lead.',
      pathParams: [],
      queryParams: [],
      requestBody: {
        nombre: 'string (requerido, max 200)',
        empresa: 'string (requerido, max 200)',
        telefono: 'string (requerido, max 50)',
        email: 'string (opcional, email válido)',
        canalOrigen: CANALES_ORIGEN,
        estadoPipeline: ESTADOS_PIPELINE,
        ticketEstimado: 'number (≥ 0)',
        prioridad: PRIORIDADES,
        localidad: 'string (opcional)',
        notas: 'string (opcional)',
        activo: 'boolean (opcional, default true)',
      },
      bodyExample: {
        nombre: 'Juan Pérez',
        empresa: 'Acme SL',
        telefono: '+34600111222',
        email: 'juan@acme.es',
        canalOrigen: 'web',
        estadoPipeline: 'nuevo',
        ticketEstimado: 5000,
        prioridad: 'media',
        localidad: 'Madrid',
        notas: 'Cliente potencial.',
        activo: true,
      },
      responseExample: { ok: true, message: 'Creado correctamente', data: { id: '...', nombre: 'Juan Pérez', empresa: '...', telefono: '...', email: '...', canalOrigen: 'web', estadoPipeline: 'nuevo', ticketEstimado: 5000, prioridad: 'media', activo: true, createdAt: '...', updatedAt: '...' } },
      prueba: `curl -s -X POST "${base}/leads/post" -H "Content-Type: application/json" -d "{\\"nombre\\":\\"Test Lead\\",\\"empresa\\":\\"Test SA\\",\\"telefono\\":\\"+34600000001\\",\\"email\\":\\"test@test.es\\",\\"canalOrigen\\":\\"web\\",\\"estadoPipeline\\":\\"nuevo\\",\\"ticketEstimado\\":0,\\"prioridad\\":\\"media\\",\\"activo\\":true}"`,
    },
    {
      metodo: 'PUT',
      ruta: '/api/v1/leads/update/:id',
      descripcion: 'Actualizar un lead (PUT o PATCH).',
      pathParams: [{ nombre: 'id', tipo: 'string', descripcion: 'ID del lead' }],
      queryParams: [],
      requestBody: '(Campos parciales permitidos en PATCH; mismos tipos que POST)',
      bodyExample: { nombre: 'Juan Pérez Actualizado', prioridad: 'alta' },
      responseExample: { ok: true, data: { id: '...', nombre: 'Juan Pérez Actualizado', empresa: '...', prioridad: 'alta', createdAt: '...', updatedAt: '...' } },
      prueba: `curl -s -X PUT "${base}/leads/update/REEMPLAZAR_ID" -H "Content-Type: application/json" -d "{\\"prioridad\\":\\"alta\\"}"`,
    },
    {
      metodo: 'DELETE',
      ruta: '/api/v1/leads/delete/:id',
      descripcion: 'Eliminar un lead.',
      pathParams: [{ nombre: 'id', tipo: 'string', descripcion: 'ID del lead' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: { id: '...' } },
      prueba: `curl -s -X DELETE "${base}/leads/delete/REEMPLAZAR_ID"`,
    },
    {
      metodo: 'POST',
      ruta: '/api/v1/leads/get/:id/convertir-cliente',
      descripcion: 'Convertir un lead en cliente. Crea el cliente con datos del lead (y payload opcional), marca el lead como inactivo y guarda clienteId.',
      pathParams: [{ nombre: 'id', tipo: 'string', descripcion: 'ID del lead' }],
      queryParams: [],
      requestBody: 'Opcional: campos de cliente para sobrescribir (nombreContacto, empresa, telefono, email, ciudad, web, estadoCliente, serviciosContratados, mrr, proximaRevision, observacionesInternas).',
      bodyExample: { estadoCliente: 'activo', serviciosContratados: ['Web'], mrr: 5000 },
      responseExample: { ok: true, message: 'Lead convertido en cliente correctamente', data: { id: '...', nombreContacto: '...', empresa: '...', leadOrigenId: '...' }, meta: { clienteId: '...' } },
      prueba: `curl -s -X POST "${base}/leads/get/REEMPLAZAR_LEAD_ID/convertir-cliente" -H "Content-Type: application/json" -d "{}"`,
    },
    // Clientes
    {
      metodo: 'GET',
      ruta: '/api/v1/clientes/get/all',
      descripcion: 'Obtener todos los clientes.',
      pathParams: [],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: [], meta: { total: 0 } },
      prueba: `curl -s "${base}/clientes/get/all"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/clientes/get/all/paginated',
      descripcion: 'Clientes paginados con filtros.',
      pathParams: [],
      queryParams: [
        { nombre: 'page', tipo: 'number', opcional: true },
        { nombre: 'limit', tipo: 'number', opcional: true },
        { nombre: 'search', tipo: 'string', opcional: true },
        { nombre: 'estadoCliente', tipo: 'string', opcional: true, enum: ['activo', 'pausado', 'finalizado'] },
        { nombre: 'servicio', tipo: 'string', opcional: true },
        { nombre: 'fechaAltaDesde', tipo: 'string', opcional: true },
        { nombre: 'fechaAltaHasta', tipo: 'string', opcional: true },
        { nombre: 'proximaRevisionDesde', tipo: 'string', opcional: true },
        { nombre: 'proximaRevisionHasta', tipo: 'string', opcional: true },
      ],
      requestBody: null,
      responseExample: { ok: true, data: [], meta: { page: 1, limit: 10, total: 0, totalPages: 0 } },
      prueba: `curl -s "${base}/clientes/get/all/paginated?page=1&limit=5"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/clientes/get/:id',
      descripcion: 'Obtener un cliente por ID.',
      pathParams: [{ nombre: 'id', tipo: 'string' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: { id: '...', nombreContacto: '...', empresa: '...', estadoCliente: 'activo', leadOrigenId: null } },
      prueba: `curl -s "${base}/clientes/get/REEMPLAZAR_ID"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/clientes/get/:id/tareas',
      descripcion: 'Tareas asociadas al cliente.',
      pathParams: [{ nombre: 'id', tipo: 'string', descripcion: 'ID del cliente' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: [], meta: { total: 0 } },
      prueba: `curl -s "${base}/clientes/get/REEMPLAZAR_CLIENTE_ID/tareas"`,
    },
    {
      metodo: 'POST',
      ruta: '/api/v1/clientes/post',
      descripcion: 'Crear un cliente. No duplicar por email/teléfono. MRR ≥ 0.',
      pathParams: [],
      queryParams: [],
      requestBody: {
        nombreContacto: 'string (requerido)',
        empresa: 'string (requerido)',
        telefono: 'string (requerido)',
        email: 'string (opcional)',
        ciudad: 'string (opcional)',
        web: 'string (opcional)',
        estadoCliente: 'activo | pausado | finalizado',
        serviciosContratados: 'array string (opcional)',
        mrr: 'number ≥ 0 (opcional)',
        proximaRevision: 'ISO date (opcional)',
        observacionesInternas: 'string (opcional)',
        leadOrigenId: 'string (opcional)',
      },
      responseExample: { ok: true, message: 'Cliente creado correctamente', data: { id: '...', nombreContacto: '...', empresa: '...' } },
      prueba: `curl -s -X POST "${base}/clientes/post" -H "Content-Type: application/json" -d "{\\"nombreContacto\\":\\"Juan\\",\\"empresa\\":\\"Acme\\",\\"telefono\\":\\"+34600111222\\",\\"email\\":\\"juan@acme.es\\",\\"estadoCliente\\":\\"activo\\"}"`,
    },
    {
      metodo: 'PUT',
      ruta: '/api/v1/clientes/update/:id',
      descripcion: 'Actualizar un cliente (PUT o PATCH).',
      pathParams: [{ nombre: 'id', tipo: 'string' }],
      queryParams: [],
      requestBody: '(Campos parciales; mismos tipos que POST)',
      responseExample: { ok: true, data: { id: '...', nombreContacto: '...', empresa: '...', updatedAt: '...' } },
      prueba: `curl -s -X PUT "${base}/clientes/update/REEMPLAZAR_ID" -H "Content-Type: application/json" -d "{\\"estadoCliente\\":\\"pausado\\"}"`,
    },
    {
      metodo: 'DELETE',
      ruta: '/api/v1/clientes/delete/:id',
      descripcion: 'Eliminar un cliente.',
      pathParams: [{ nombre: 'id', tipo: 'string' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: { id: '...' } },
      prueba: `curl -s -X DELETE "${base}/clientes/delete/REEMPLAZAR_ID"`,
    },
    // Interacciones
    {
      metodo: 'GET',
      ruta: '/api/v1/interacciones/get/all',
      descripcion: 'Obtener todas las interacciones.',
      pathParams: [],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: [] },
      prueba: `curl -s "${base}/interacciones/get/all"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/interacciones/get/all/paginated',
      descripcion: 'Interacciones paginadas con filtros.',
      pathParams: [],
      queryParams: [
        { nombre: 'page', tipo: 'number', opcional: true },
        { nombre: 'limit', tipo: 'number', opcional: true },
        { nombre: 'leadId', tipo: 'string', opcional: true },
        { nombre: 'tipo', tipo: 'string', opcional: true, enum: TIPOS_INT },
        { nombre: 'resultado', tipo: 'string', opcional: true, enum: RESULTADOS },
      ],
      requestBody: null,
      responseExample: { ok: true, data: [], meta: { page: 1, limit: 10, total: 0, totalPages: 0 } },
      prueba: `curl -s "${base}/interacciones/get/all/paginated?page=1&limit=5"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/interacciones/get/:id',
      descripcion: 'Obtener una interacción por ID.',
      pathParams: [{ nombre: 'id', tipo: 'string' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: { id: '...', leadId: '...', tipo: 'llamada', direccion: 'saliente', resumen: '...', resultado: 'respondio', fechaInteraccion: '...', createdAt: '...', updatedAt: '...' } },
      prueba: `curl -s "${base}/interacciones/get/REEMPLAZAR_ID"`,
    },
    {
      metodo: 'POST',
      ruta: '/api/v1/interacciones/post',
      descripcion: 'Crear una interacción.',
      pathParams: [],
      queryParams: [],
      requestBody: {
        leadId: 'string (requerido)',
        tipo: TIPOS_INT,
        direccion: DIRECCIONES,
        resumen: 'string (requerido, max 2000)',
        resultado: RESULTADOS,
        fechaInteraccion: 'string ISO fecha (requerido)',
        proximaAccionFecha: 'string ISO fecha (opcional, ≥ fechaInteraccion)',
        duracionMin: 'number ≥ 0 (opcional)',
      },
      bodyExample: {
        leadId: 'ID_LEAD_EXISTENTE',
        tipo: 'llamada',
        direccion: 'saliente',
        resumen: 'Llamada de seguimiento',
        resultado: 'respondio',
        fechaInteraccion: new Date().toISOString(),
        proximaAccionFecha: null,
        duracionMin: 5,
      },
      responseExample: { ok: true, message: 'Creado correctamente', data: { id: '...', leadId: '...', tipo: 'nota', resumen: 'Nota de prueba', resultado: 'pendiente', fechaInteraccion: '...', createdAt: '...', updatedAt: '...' } },
      prueba: `curl -s -X POST "${base}/interacciones/post" -H "Content-Type: application/json" -d "{\\"leadId\\":\\"REEMPLAZAR_LEAD_ID\\",\\"tipo\\":\\"nota\\",\\"direccion\\":\\"saliente\\",\\"resumen\\":\\"Nota de prueba\\",\\"resultado\\":\\"pendiente\\",\\"fechaInteraccion\\":\\"${new Date().toISOString()}\\"}"`,
    },
    {
      metodo: 'PUT',
      ruta: '/api/v1/interacciones/update/:id',
      descripcion: 'Actualizar una interacción (PUT o PATCH).',
      pathParams: [{ nombre: 'id', tipo: 'string' }],
      queryParams: [],
      requestBody: '(Campos parciales; mismos tipos que POST)',
      responseExample: { ok: true, data: { id: '...', leadId: '...', tipo: 'llamada', resumen: 'Resumen actualizado', resultado: '...', createdAt: '...', updatedAt: '...' } },
      prueba: `curl -s -X PUT "${base}/interacciones/update/REEMPLAZAR_ID" -H "Content-Type: application/json" -d "{\\"resumen\\":\\"Resumen actualizado\\"}"`,
    },
    {
      metodo: 'DELETE',
      ruta: '/api/v1/interacciones/delete/:id',
      descripcion: 'Eliminar una interacción.',
      pathParams: [{ nombre: 'id', tipo: 'string' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: { id: '...' } },
      prueba: `curl -s -X DELETE "${base}/interacciones/delete/REEMPLAZAR_ID"`,
    },
    // Tareas
    {
      metodo: 'GET',
      ruta: '/api/v1/tareas/get/all',
      descripcion: 'Obtener todas las tareas.',
      pathParams: [],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: [] },
      prueba: `curl -s "${base}/tareas/get/all"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/tareas/get/all/paginated',
      descripcion: 'Tareas paginadas con filtros.',
      pathParams: [],
      queryParams: [
        { nombre: 'page', tipo: 'number', opcional: true },
        { nombre: 'limit', tipo: 'number', opcional: true },
        { nombre: 'estado', tipo: 'string', opcional: true, enum: ESTADOS_TAREA },
        { nombre: 'prioridad', tipo: 'string', opcional: true, enum: PRIORIDADES },
        { nombre: 'leadId', tipo: 'string', opcional: true },
        { nombre: 'clienteId', tipo: 'string', opcional: true },
        { nombre: 'categoriaPlanificacion', tipo: 'string', opcional: true, enum: ['diaria', 'semanal', 'puntual'] },
      ],
      requestBody: null,
      responseExample: { ok: true, data: [], meta: { page: 1, limit: 10, total: 0, totalPages: 0 } },
      prueba: `curl -s "${base}/tareas/get/all/paginated?page=1&limit=5"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/tareas/get/upcoming',
      descripcion: 'Tareas próximas (por días).',
      pathParams: [],
      queryParams: [{ nombre: 'days', tipo: 'number', opcional: true, ejemplo: '7', descripcion: 'Días hacia adelante' }],
      requestBody: null,
      responseExample: { ok: true, data: [] },
      prueba: `curl -s "${base}/tareas/get/upcoming?days=7"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/tareas/get/today',
      descripcion: 'Tareas de hoy: recordatorio o vencimiento = hoy, ordenadas por hora de cierre (asc).',
      pathParams: [],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: [], meta: { total: 0 } },
      prueba: `curl -s "${base}/tareas/get/today"`,
    },
    {
      metodo: 'GET',
      ruta: '/api/v1/tareas/get/:id',
      descripcion: 'Obtener una tarea por ID.',
      pathParams: [{ nombre: 'id', tipo: 'string' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: { id: '...', titulo: '...', descripcion: '...', tipo: 'seguimiento', estado: 'pendiente', prioridad: 'media', leadId: null, fechaVencimiento: null, completada: false, createdAt: '...', updatedAt: '...' } },
      prueba: `curl -s "${base}/tareas/get/REEMPLAZAR_ID"`,
    },
    {
      metodo: 'POST',
      ruta: '/api/v1/tareas/post',
      descripcion: 'Crear una tarea.',
      pathParams: [],
      queryParams: [],
      requestBody: {
        titulo: 'string (requerido, max 200)',
        descripcion: 'string (opcional)',
        tipo: TIPOS_TAREA,
        estado: ESTADOS_TAREA,
        prioridad: PRIORIDADES,
        leadId: 'string | null (opcional, debe existir si se envía)',
        fechaVencimiento: 'string ISO fecha (opcional)',
        fechaRecordatorio: 'string ISO fecha (opcional, ≤ fechaVencimiento)',
        completada: 'boolean (opcional, default false)',
      },
      bodyExample: {
        titulo: 'Llamar al cliente',
        descripcion: 'Seguimiento post-reunión',
        tipo: 'seguimiento',
        estado: 'pendiente',
        prioridad: 'media',
        leadId: null,
        fechaVencimiento: new Date(Date.now() + 86400000).toISOString(),
        fechaRecordatorio: null,
        completada: false,
      },
      responseExample: { ok: true, message: 'Creado correctamente', data: { id: '...', titulo: 'Tarea de prueba', tipo: 'recordatorio', estado: 'pendiente', prioridad: 'baja', completada: false, createdAt: '...', updatedAt: '...' } },
      prueba: `curl -s -X POST "${base}/tareas/post" -H "Content-Type: application/json" -d "{\\"titulo\\":\\"Tarea de prueba\\",\\"descripcion\\":\\"\\",\\"tipo\\":\\"recordatorio\\",\\"estado\\":\\"pendiente\\",\\"prioridad\\":\\"baja\\",\\"completada\\":false}"`,
    },
    {
      metodo: 'PUT',
      ruta: '/api/v1/tareas/update/:id',
      descripcion: 'Actualizar una tarea (PUT o PATCH).',
      pathParams: [{ nombre: 'id', tipo: 'string' }],
      queryParams: [],
      requestBody: '(Campos parciales; mismos tipos que POST)',
      responseExample: { ok: true, data: { id: '...', titulo: '...', estado: 'hecha', completada: true, updatedAt: '...' } },
      prueba: `curl -s -X PUT "${base}/tareas/update/REEMPLAZAR_ID" -H "Content-Type: application/json" -d "{\\"estado\\":\\"hecha\\",\\"completada\\":true}"`,
    },
    {
      metodo: 'DELETE',
      ruta: '/api/v1/tareas/delete/:id',
      descripcion: 'Eliminar una tarea.',
      pathParams: [{ nombre: 'id', tipo: 'string' }],
      queryParams: [],
      requestBody: null,
      responseExample: { ok: true, data: { id: '...' } },
      prueba: `curl -s -X DELETE "${base}/tareas/delete/REEMPLAZAR_ID"`,
    },
    // Dashboard
    {
      metodo: 'GET',
      ruta: '/api/v1/dashboard/summary',
      descripcion: 'Resumen del dashboard: KPIs (totalLeads, leadsActivos, clientesActivos, tareasPendientesHoy, tareasVencidas, conversionLeadCliente, reunionesSemana), leadsRecientes, proximasTareas, tareasHoy, actividadReciente (timeline).',
      pathParams: [],
      queryParams: [
        { nombre: 'limitLeads', tipo: 'number', opcional: true, ejemplo: '10' },
        { nombre: 'limitTareas', tipo: 'number', opcional: true, ejemplo: '15' },
        { nombre: 'limitActividad', tipo: 'number', opcional: true, ejemplo: '20' },
      ],
      requestBody: null,
      responseExample: {
        ok: true,
        data: {
          totalLeads: 20,
          leadsActivos: 15,
          clientesActivos: 5,
          tareasPendientes: 8,
          tareasPendientesHoy: 3,
          tareasVencidas: 1,
          conversionLeadCliente: 0.15,
          reunionesSemana: 2,
          leadsRecientes: [],
          proximasTareas: [],
          tareasHoy: [],
          actividadReciente: [],
        },
      },
      prueba: `curl -s "${base}/dashboard/summary"`,
    },
  ];

  return {
    proyecto: 'NakedCRM Lite',
    version: '1.0.0',
    baseUrl: baseUrl,
    basePath: '/api/v1',
    descripcion: 'API REST para gestión de leads, interacciones y tareas. CRUD completo por recurso, paginación, filtros y reglas de negocio.',
    reglasNegocio: reglasNegocio,
    formatosRespuesta: {
      exito: { ok: true, message: 'string opcional', data: 'objeto o array', meta: 'opcional (paginación)' },
      error: { ok: false, message: 'string', errors: 'array opcional [{ field, message }]' },
      codigosHttp: { 200: 'OK', 201: 'Creado', 400: 'Error validación/solicitud', 404: 'No encontrado', 500: 'Error servidor' },
    },
    endpoints: endpoints,
    pruebas: 'Cada endpoint incluye el campo "prueba" con un comando curl. Reemplaza REEMPLAZAR_ID o REEMPLAZAR_LEAD_ID por IDs reales obtenidos de GET /leads/get/all o similares.',
  };
}

module.exports = { buildDoc, reglasNegocio };
